language: generic

sudo: required

services:
  - docker


before_install:
  - docker build -t seor8674/react-test-app -f ./frontend/Docker.dev ./frontend

script:
  - docker run -e CI=true seor8674/react-test-app npm run test

after_success:
  - docker build -t seor8674/docker-frontend ./frontend
  - docker build -t seor8674/docker-backend ./backend
  - docker build -t seor8674/docker-nginx ./nginx

  -echo "$DOCKER_HUB-PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  -docker push seor8674/docker-frontend
  -docker push seor8674/docker-backend
  -docker push seor8674/docker-nginx
  